apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  lables:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node-role: worker
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80